//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NovaParser.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INovaParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class NovaParserBaseListener : INovaParserListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryValue</c>
	/// labeled alternative in <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryValue([NotNull] NovaParser.PrimaryValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryValue</c>
	/// labeled alternative in <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryValue([NotNull] NovaParser.PrimaryValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>opExpr</c>
	/// labeled alternative in <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpExpr([NotNull] NovaParser.OpExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>opExpr</c>
	/// labeled alternative in <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpExpr([NotNull] NovaParser.OpExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>stExpr</c>
	/// labeled alternative in <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStExpr([NotNull] NovaParser.StExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stExpr</c>
	/// labeled alternative in <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStExpr([NotNull] NovaParser.StExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] NovaParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] NovaParser.CompilationUnitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportDeclaration([NotNull] NovaParser.ImportDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportDeclaration([NotNull] NovaParser.ImportDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] NovaParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] NovaParser.TypeDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] NovaParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] NovaParser.ClassDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaration([NotNull] NovaParser.StructDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaration([NotNull] NovaParser.StructDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] NovaParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] NovaParser.ClassBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDeclaration([NotNull] NovaParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDeclaration([NotNull] NovaParser.MemberDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] NovaParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] NovaParser.ModifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.classModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassModifier([NotNull] NovaParser.ClassModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.classModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassModifier([NotNull] NovaParser.ClassModifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaration([NotNull] NovaParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaration([NotNull] NovaParser.FieldDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] NovaParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] NovaParser.VariableDeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableInitializer([NotNull] NovaParser.VariableInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableInitializer([NotNull] NovaParser.VariableInitializerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaratorId([NotNull] NovaParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaratorId([NotNull] NovaParser.VariableDeclaratorIdContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeType([NotNull] NovaParser.TypeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeType([NotNull] NovaParser.TypeTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] NovaParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] NovaParser.PrimitiveTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] NovaParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] NovaParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] NovaParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] NovaParser.MethodDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.typeTypeOrUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeTypeOrUnit([NotNull] NovaParser.TypeTypeOrUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.typeTypeOrUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeTypeOrUnit([NotNull] NovaParser.TypeTypeOrUnitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameters([NotNull] NovaParser.FormalParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameters([NotNull] NovaParser.FormalParametersContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterList([NotNull] NovaParser.FormalParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterList([NotNull] NovaParser.FormalParameterListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameter([NotNull] NovaParser.FormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameter([NotNull] NovaParser.FormalParameterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLastFormalParameter([NotNull] NovaParser.LastFormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLastFormalParameter([NotNull] NovaParser.LastFormalParameterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorDeclaration([NotNull] NovaParser.ConstructorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorDeclaration([NotNull] NovaParser.ConstructorDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodBody([NotNull] NovaParser.MethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodBody([NotNull] NovaParser.MethodBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] NovaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] NovaParser.BlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclaration([NotNull] NovaParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclaration([NotNull] NovaParser.LocalVariableDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] NovaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] NovaParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.assignationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignationStatement([NotNull] NovaParser.AssignationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.assignationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignationStatement([NotNull] NovaParser.AssignationStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.statementExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementExpression([NotNull] NovaParser.StatementExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.statementExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementExpression([NotNull] NovaParser.StatementExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] NovaParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] NovaParser.IfStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] NovaParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] NovaParser.ForStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParExpression([NotNull] NovaParser.ParExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParExpression([NotNull] NovaParser.ParExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForControl([NotNull] NovaParser.ForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForControl([NotNull] NovaParser.ForControlContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForInit([NotNull] NovaParser.ForInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForInit([NotNull] NovaParser.ForInitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] NovaParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] NovaParser.ExpressionListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] NovaParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] NovaParser.PrimaryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] NovaParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] NovaParser.LiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] NovaParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] NovaParser.IntegerLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteral([NotNull] NovaParser.FloatLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteral([NotNull] NovaParser.FloatLiteralContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] NovaParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] NovaParser.MethodCallContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.constructorCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorCall([NotNull] NovaParser.ConstructorCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.constructorCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorCall([NotNull] NovaParser.ConstructorCallContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.nativeCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNativeCall([NotNull] NovaParser.NativeCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.nativeCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNativeCall([NotNull] NovaParser.NativeCallContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreator([NotNull] NovaParser.CreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreator([NotNull] NovaParser.CreatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatedName([NotNull] NovaParser.CreatedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatedName([NotNull] NovaParser.CreatedNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassCreatorRest([NotNull] NovaParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassCreatorRest([NotNull] NovaParser.ClassCreatorRestContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="NovaParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] NovaParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NovaParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] NovaParser.ArgumentsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
